apiVersion: v1
kind: Namespace
metadata:
  name: eagle-bank-local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eagle-bank-config
  namespace: eagle-bank-local
data:
  SPRING_PROFILES_ACTIVE: "local"
  DB_NAME: "eaglebank"
---
apiVersion: v1
kind: Secret
metadata:
  name: eagle-bank-secrets
  namespace: eagle-bank-local
type: Opaque
data:
  DB_PASSWORD: eW91cl9zZWN1cmVfcGFzc3dvcmQ=  # your_secure_password
  DB_USER: ZWFnbGViYW5rX3VzZXI=             # eaglebank_user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eagle-bank-db
  namespace: eagle-bank-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eagle-bank-db
  template:
    metadata:
      labels:
        app: eagle-bank-db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: eaglebank
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: eagle-bank-secrets
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eagle-bank-secrets
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: eagle-bank-db
  namespace: eagle-bank-local
spec:
  selector:
    app: eagle-bank-db
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eagle-bank
  namespace: eagle-bank-local
spec:
  replicas: 1  # Single replica for local development
  selector:
    matchLabels:
      app: eagle-bank
  template:
    metadata:
      labels:
        app: eagle-bank
    spec:
      containers:
      - name: eagle-bank
        image: eagle-bank:latest  # We'll build this locally
        imagePullPolicy: Never   # Important for local development
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://eagle-bank-db:5432/eaglebank
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: eagle-bank-secrets
              key: DB_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eagle-bank-secrets
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: eagle-bank
  namespace: eagle-bank-local
spec:
  type: LoadBalancer  # This makes it accessible locally
  selector:
    app: eagle-bank
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eagle-bank-frontend
  namespace: eagle-bank-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eagle-bank-frontend
  template:
    metadata:
      labels:
        app: eagle-bank-frontend
    spec:
      containers:
        - name: eagle-bank-frontend
          image: eagle-bank-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: eagle-bank-frontend
  namespace: eagle-bank-local
spec:
  type: LoadBalancer
  selector:
    app: eagle-bank-frontend
  ports:
    - port: 80
      targetPort: 80